version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapea el puerto 3000 del contenedor al 3000 del host
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
